<?php

namespace Valpuia\Mizokhua\Database\Seeders\Villages;

use Illuminate\Database\Seeder;
use Valpuia\Mizokhua\Models\Village;

class LawngtlaiDistrictVillageSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $villages = [
            ['id' => '261', 'district_id' => '6', 'name' => 'Adubangasora'],
            ['id' => '262', 'district_id' => '6', 'name' => 'Ajasora-I'],
            ['id' => '263', 'district_id' => '6', 'name' => 'Ajasora II'],
            ['id' => '264', 'district_id' => '6', 'name' => 'Ajasora III'],
            ['id' => '265', 'district_id' => '6', 'name' => 'Aoc Veng'],
            ['id' => '266', 'district_id' => '6', 'name' => 'Archhuang'],
            ['id' => '267', 'district_id' => '6', 'name' => 'Arotinagar'],
            ['id' => '268', 'district_id' => '6', 'name' => 'Baganpara'],
            ['id' => '269', 'district_id' => '6', 'name' => 'Bajeisora'],
            ['id' => '270', 'district_id' => '6', 'name' => 'Bandukbanga'],
            ['id' => '271', 'district_id' => '6', 'name' => 'Baraguisury'],
            ['id' => '272', 'district_id' => '6', 'name' => 'Barapansury East'],
            ['id' => '273', 'district_id' => '6', 'name' => 'Barapansury-I'],
            ['id' => '274', 'district_id' => '6', 'name' => 'Barapansury-Ii'],
            ['id' => '275', 'district_id' => '6', 'name' => 'Barkalak'],
            ['id' => '276', 'district_id' => '6', 'name' => 'Barkobakhali'],
            ['id' => '277', 'district_id' => '6', 'name' => 'Barkobakhali-Ii'],
            ['id' => '278', 'district_id' => '6', 'name' => 'Betbonya'],
            ['id' => '279', 'district_id' => '6', 'name' => 'Billosora'],
            ['id' => '280', 'district_id' => '6', 'name' => 'Bolisora'],
            ['id' => '281', 'district_id' => '6', 'name' => 'Boranasury'],
            ['id' => '282', 'district_id' => '6', 'name' => 'Boroituli'],
            ['id' => '283', 'district_id' => '6', 'name' => 'Bualpui Ng-I'],
            ['id' => '284', 'district_id' => '6', 'name' => 'Bualpui Ng-Ii'],
            ['id' => '285', 'district_id' => '6', 'name' => 'Bungtlang S-I'],
            ['id' => '286', 'district_id' => '6', 'name' => 'Bungtlang S-Ii'],
            ['id' => '287', 'district_id' => '6', 'name' => 'Chamdur P I'],
            ['id' => '288', 'district_id' => '6', 'name' => 'Chamdur P II'],
            ['id' => '289', 'district_id' => '6', 'name' => 'Chamdurtlang I'],
            ['id' => '290', 'district_id' => '6', 'name' => 'Chamdurtlang II'],
            ['id' => '291', 'district_id' => '6', 'name' => 'Chaminisora'],
            ['id' => '292', 'district_id' => '6', 'name' => 'Charluitlang'],
            ['id' => '293', 'district_id' => '6', 'name' => 'Chawngtelui'],
            ['id' => '294', 'district_id' => '6', 'name' => 'Chawngte P'],
            ['id' => '295', 'district_id' => '6', 'name' => 'Chawnhu'],
            ['id' => '296', 'district_id' => '6', 'name' => 'Chawntlangpui'],
            ['id' => '297', 'district_id' => '6', 'name' => 'Cheural'],
            ['id' => '298', 'district_id' => '6', 'name' => 'Chikhurlui'],
            ['id' => '299', 'district_id' => '6', 'name' => 'Chongrasury'],
            ['id' => '300', 'district_id' => '6', 'name' => 'Chotapansury'],
            ['id' => '301', 'district_id' => '6', 'name' => 'Chotobokhali'],
            ['id' => '302', 'district_id' => '6', 'name' => 'Chotoguisury-I'],
            ['id' => '303', 'district_id' => '6', 'name' => 'Chotoguisury-Ii'],
            ['id' => '304', 'district_id' => '6', 'name' => 'College Veng'],
            ['id' => '305', 'district_id' => '6', 'name' => 'Council Veng'],
            ['id' => '306', 'district_id' => '6', 'name' => 'Damlui'],
            ['id' => '307', 'district_id' => '6', 'name' => 'Darnamtlang'],
            ['id' => '308', 'district_id' => '6', 'name' => 'Devasora N'],
            ['id' => '309', 'district_id' => '6', 'name' => 'Devasora S'],
            ['id' => '310', 'district_id' => '6', 'name' => 'Diltlang S'],
            ['id' => '311', 'district_id' => '6', 'name' => 'Dumzautlang'],
            ['id' => '312', 'district_id' => '6', 'name' => 'Dursora'],
            ['id' => '313', 'district_id' => '6', 'name' => 'Electric Veng'],
            ['id' => '314', 'district_id' => '6', 'name' => 'Fangfarlui'],
            ['id' => '315', 'district_id' => '6', 'name' => 'Fulsora'],
            ['id' => '316', 'district_id' => '6', 'name' => 'Fultuli'],
            ['id' => '317', 'district_id' => '6', 'name' => 'Futsury'],
            ['id' => '318', 'district_id' => '6', 'name' => 'Gabasury'],
            ['id' => '319', 'district_id' => '6', 'name' => 'Gerakuluksora'],
            ['id' => '320', 'district_id' => '6', 'name' => 'Gerasury'],
            ['id' => '321', 'district_id' => '6', 'name' => 'Golasury'],
            ['id' => '322', 'district_id' => '6', 'name' => 'Gulsingbapsora'],
            ['id' => '323', 'district_id' => '6', 'name' => 'Hmawngbu'],
            ['id' => '324', 'district_id' => '6', 'name' => 'Hmawngbuchhuah'],
            ['id' => '325', 'district_id' => '6', 'name' => 'Hmunlai'],
            ['id' => '326', 'district_id' => '6', 'name' => 'Hmunnuam'],
            ['id' => '327', 'district_id' => '6', 'name' => 'Hruitezawl'],
            ['id' => '328', 'district_id' => '6', 'name' => 'Jamersury'],
            ['id' => '329', 'district_id' => '6', 'name' => 'Jaruldubosora'],
            ['id' => '330', 'district_id' => '6', 'name' => 'Jarulsury'],
            ['id' => '331', 'district_id' => '6', 'name' => 'Jarulsury-Ii'],
            ['id' => '332', 'district_id' => '6', 'name' => 'Jognasuri'],
            ['id' => '333', 'district_id' => '6', 'name' => 'Jognasury II'],
            ['id' => '334', 'district_id' => '6', 'name' => 'Kakichhuah'],
            ['id' => '335', 'district_id' => '6', 'name' => 'Kamalanagar-I'],
            ['id' => '336', 'district_id' => '6', 'name' => 'Kamalanagar II'],
            ['id' => '337', 'district_id' => '6', 'name' => 'Kamalanagar III'],
            ['id' => '338', 'district_id' => '6', 'name' => 'Kamalanagar IV'],
            ['id' => '339', 'district_id' => '6', 'name' => 'Kamalanagar V'],
            ['id' => '340', 'district_id' => '6', 'name' => 'Kamalanagar VI'],
            ['id' => '341', 'district_id' => '6', 'name' => 'Kamtuli'],
            ['id' => '342', 'district_id' => '6', 'name' => 'Karlui I'],
            ['id' => '343', 'district_id' => '6', 'name' => 'Karlui II'],
            ['id' => '344', 'district_id' => '6', 'name' => 'Kawlchaw W'],
            ['id' => '345', 'district_id' => '6', 'name' => 'Kawnkhua'],
            ['id' => '346', 'district_id' => '6', 'name' => 'Kawrthindeng'],
            ['id' => '347', 'district_id' => '6', 'name' => 'Kukurduleya'],
            ['id' => '348', 'district_id' => '6', 'name' => 'Kurbalovasora'],
            ['id' => '349', 'district_id' => '6', 'name' => 'Laitlang'],
            ['id' => '350', 'district_id' => '6', 'name' => 'Lakkisury'],
            ['id' => '351', 'district_id' => '6', 'name' => 'Lawngtlai II (Bazar Veng)'],
            ['id' => '352', 'district_id' => '6', 'name' => 'Lawngtlai III'],
            ['id' => '353', 'district_id' => '6', 'name' => 'Lawngtlai IV (Chanmary - I)'],
            ['id' => '354', 'district_id' => '6', 'name' => 'Lawngtlai IV (Chanmary - Ii)'],
            ['id' => '355', 'district_id' => '6', 'name' => 'Lawngtlai I (Vengpui - I)'],
            ['id' => '356', 'district_id' => '6', 'name' => 'Lawngtlai I (Vengpui - Ii)'],
            ['id' => '357', 'district_id' => '6', 'name' => 'Longpuighat'],
            ['id' => '358', 'district_id' => '6', 'name' => 'Longpuighat-Ii'],
            ['id' => '359', 'district_id' => '6', 'name' => 'Ludisora'],
            ['id' => '360', 'district_id' => '6', 'name' => 'Lunghauka'],
            ['id' => '361', 'district_id' => '6', 'name' => 'Lungpher S'],
            ['id' => '362', 'district_id' => '6', 'name' => 'Lungtian I'],
            ['id' => '363', 'district_id' => '6', 'name' => 'Lungtian II'],
            ['id' => '364', 'district_id' => '6', 'name' => 'Lungzarhtum'],
            ['id' => '365', 'district_id' => '6', 'name' => 'Mainabapsora I'],
            ['id' => '366', 'district_id' => '6', 'name' => 'Mainabapsora-Ii'],
            ['id' => '367', 'district_id' => '6', 'name' => 'Mampui'],
            ['id' => '368', 'district_id' => '6', 'name' => 'Mandirasora'],
            ['id' => '369', 'district_id' => '6', 'name' => 'Massury'],
            ['id' => '370', 'district_id' => '6', 'name' => 'Mautlang (Lawngtlai)'],
            ['id' => '371', 'district_id' => '6', 'name' => 'M.Kawnpui'],
            ['id' => '372', 'district_id' => '6', 'name' => 'Montola'],
            ['id' => '373', 'district_id' => '6', 'name' => 'Mualbu L'],
            ['id' => '374', 'district_id' => '6', 'name' => 'Nagdarasora'],
            ['id' => '375', 'district_id' => '6', 'name' => 'Nalbonya'],
            ['id' => '376', 'district_id' => '6', 'name' => 'New Jaganasury-I'],
            ['id' => '377', 'district_id' => '6', 'name' => 'New Jaganasury-Ii'],
            ['id' => '378', 'district_id' => '6', 'name' => 'New Jaganasury-Iii'],
            ['id' => '379', 'district_id' => '6', 'name' => 'Ngengpuikai'],
            ['id' => '380', 'district_id' => '6', 'name' => 'Ngengpuitlang'],
            ['id' => '381', 'district_id' => '6', 'name' => 'Nghalimlui'],
            ['id' => '382', 'district_id' => '6', 'name' => 'Ngunlingkhua'],
            ['id' => '383', 'district_id' => '6', 'name' => 'Old Bajeisora'],
            ['id' => '384', 'district_id' => '6', 'name' => 'Paithar'],
            ['id' => '385', 'district_id' => '6', 'name' => 'Palenosora'],
            ['id' => '386', 'district_id' => '6', 'name' => 'Pandawnglui'],
            ['id' => '387', 'district_id' => '6', 'name' => 'Pangkhua'],
            ['id' => '388', 'district_id' => '6', 'name' => 'Parva I'],
            ['id' => '389', 'district_id' => '6', 'name' => 'Parva II'],
            ['id' => '390', 'district_id' => '6', 'name' => 'Parva III'],
            ['id' => '391', 'district_id' => '6', 'name' => 'Parva-Iv'],
            ['id' => '392', 'district_id' => '6', 'name' => 'Rajamandal'],
            ['id' => '393', 'district_id' => '6', 'name' => 'Rawlbuk'],
            ['id' => '394', 'district_id' => '6', 'name' => 'Rengkashya'],
            ['id' => '395', 'district_id' => '6', 'name' => 'Rulkual'],
            ['id' => '396', 'district_id' => '6', 'name' => 'R Vanhne'],
            ['id' => '397', 'district_id' => '6', 'name' => 'Sabualtlang'],
            ['id' => '398', 'district_id' => '6', 'name' => 'Saibawh'],
            ['id' => '399', 'district_id' => '6', 'name' => 'Saibawh II'],
            ['id' => '400', 'district_id' => '6', 'name' => 'Saikah L'],
            ['id' => '401', 'district_id' => '6', 'name' => 'Saikah U'],
            ['id' => '402', 'district_id' => '6', 'name' => 'Saikhawthlir (Lawngtlai)'],
            ['id' => '403', 'district_id' => '6', 'name' => 'Saizawh E'],
            ['id' => '404', 'district_id' => '6', 'name' => 'Sakeilui I'],
            ['id' => '405', 'district_id' => '6', 'name' => 'Sakeilui II'],
            ['id' => '406', 'district_id' => '6', 'name' => 'Samuksora'],
            ['id' => '407', 'district_id' => '6', 'name' => 'Sangau I'],
            ['id' => '408', 'district_id' => '6', 'name' => 'Sangau II'],
            ['id' => '409', 'district_id' => '6', 'name' => 'Sangau III'],
            ['id' => '410', 'district_id' => '6', 'name' => 'Sangau IV'],
            ['id' => '411', 'district_id' => '6', 'name' => 'Sentetfiang'],
            ['id' => '412', 'district_id' => '6', 'name' => 'Siachangkawn'],
            ['id' => '413', 'district_id' => '6', 'name' => 'Sihtlangpui'],
            ['id' => '414', 'district_id' => '6', 'name' => 'Silbanga'],
            ['id' => '415', 'district_id' => '6', 'name' => 'Sillosora'],
            ['id' => '416', 'district_id' => '6', 'name' => 'Silsury'],
            ['id' => '417', 'district_id' => '6', 'name' => 'Simeisury'],
            ['id' => '418', 'district_id' => '6', 'name' => 'Siminasora'],
            ['id' => '419', 'district_id' => '6', 'name' => 'Sumsilui'],
            ['id' => '420', 'district_id' => '6', 'name' => 'T Dumzau'],
            ['id' => '421', 'district_id' => '6', 'name' => 'Thaltlang'],
            ['id' => '422', 'district_id' => '6', 'name' => 'Thingkah'],
            ['id' => '423', 'district_id' => '6', 'name' => 'Tialdawngilung'],
            ['id' => '424', 'district_id' => '6', 'name' => 'Tuichawngtlang'],
            ['id' => '425', 'district_id' => '6', 'name' => 'Tuidangtlang'],
            ['id' => '426', 'district_id' => '6', 'name' => 'Tuikhurlui'],
            ['id' => '427', 'district_id' => '6', 'name' => 'Tuisentlang'],
            ['id' => '428', 'district_id' => '6', 'name' => 'Tuithumhnar'],
            ['id' => '429', 'district_id' => '6', 'name' => 'Tungosora'],
            ['id' => '430', 'district_id' => '6', 'name' => 'Udalthana I'],
            ['id' => '431', 'district_id' => '6', 'name' => 'Udalthana II'],
            ['id' => '432', 'district_id' => '6', 'name' => 'Ugalsury'],
            ['id' => '433', 'district_id' => '6', 'name' => 'Ugudasury N'],
            ['id' => '434', 'district_id' => '6', 'name' => 'Ugudasury S'],
            ['id' => '435', 'district_id' => '6', 'name' => 'Ulusury'],
            ['id' => '436', 'district_id' => '6', 'name' => 'Vartek'],
            ['id' => '437', 'district_id' => '6', 'name' => 'Vartekkai'],
            ['id' => '438', 'district_id' => '6', 'name' => 'Vaseitlang I'],
            ['id' => '439', 'district_id' => '6', 'name' => 'Vaseitlang II'],
            ['id' => '440', 'district_id' => '6', 'name' => 'Vathuampui'],
            ['id' => '441', 'district_id' => '6', 'name' => 'Vawmbuk'],
            ['id' => '442', 'district_id' => '6', 'name' => 'Vawmbuk-II (Vaivakawn)'],
            ['id' => '443', 'district_id' => '6', 'name' => 'Veseikai'],
            ['id' => '444', 'district_id' => '6', 'name' => 'W.Saizawh'],
            ['id' => '445', 'district_id' => '6', 'name' => 'Zochachhuah'],
        ];

        Village::upsert($villages, ['id']);
    }
}
