<?php

namespace Valpuia\Mizokhua\Database\Seeders\Villages;

use Illuminate\Database\Seeder;
use Valpuia\Mizokhua\Models\Village;

class MamitDistrictVillageSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $villages = [
            ['id' => '576', 'district_id' => '8', 'name' => 'Ailawng'],
            ['id' => '577', 'district_id' => '8', 'name' => 'Andermanik'],
            ['id' => '578', 'district_id' => '8', 'name' => 'Bawlte'],
            ['id' => '579', 'district_id' => '8', 'name' => 'Bawngthah'],
            ['id' => '580', 'district_id' => '8', 'name' => 'Bawngva'],
            ['id' => '581', 'district_id' => '8', 'name' => 'Belkhai'],
            ['id' => '582', 'district_id' => '8', 'name' => 'Borai'],
            ['id' => '583', 'district_id' => '8', 'name' => 'Bunghmun West'],
            ['id' => '584', 'district_id' => '8', 'name' => 'Bungthuam'],
            ['id' => '585', 'district_id' => '8', 'name' => 'Chhippui - I'],
            ['id' => '586', 'district_id' => '8', 'name' => 'Chhippui - II'],
            ['id' => '587', 'district_id' => '8', 'name' => 'Chilui'],
            ['id' => '588', 'district_id' => '8', 'name' => 'Chuhvel'],
            ['id' => '589', 'district_id' => '8', 'name' => 'Chungtlang'],
            ['id' => '590', 'district_id' => '8', 'name' => 'Damdiai'],
            ['id' => '591', 'district_id' => '8', 'name' => 'Damparengpui'],
            ['id' => '592', 'district_id' => '8', 'name' => 'Dampui'],
            ['id' => '593', 'district_id' => '8', 'name' => 'Dapchhuah'],
            ['id' => '594', 'district_id' => '8', 'name' => 'Darlak'],
            ['id' => '595', 'district_id' => '8', 'name' => 'Darlung'],
            ['id' => '596', 'district_id' => '8', 'name' => 'Dilzawl'],
            ['id' => '597', 'district_id' => '8', 'name' => 'Hmunpui'],
            ['id' => '598', 'district_id' => '8', 'name' => 'Hnahva'],
            ['id' => '599', 'district_id' => '8', 'name' => 'Hreichuk'],
            ['id' => '600', 'district_id' => '8', 'name' => 'Hriphaw'],
            ['id' => '601', 'district_id' => '8', 'name' => 'Hruaitluang'],
            ['id' => '602', 'district_id' => '8', 'name' => 'Hruiduk'],
            ['id' => '603', 'district_id' => '8', 'name' => 'Kananthar'],
            ['id' => '604', 'district_id' => '8', 'name' => 'Kanghmun'],
            ['id' => '605', 'district_id' => '8', 'name' => 'Kanhmun'],
            ['id' => '606', 'district_id' => '8', 'name' => 'Kawrtethawveng'],
            ['id' => '607', 'district_id' => '8', 'name' => 'Kawrthah North'],
            ['id' => '608', 'district_id' => '8', 'name' => 'Kawrthah South'],
            ['id' => '609', 'district_id' => '8', 'name' => 'Khanthuam'],
            ['id' => '610', 'district_id' => '8', 'name' => 'Khantlang'],
            ['id' => '611', 'district_id' => '8', 'name' => 'Khawhnai'],
            ['id' => '612', 'district_id' => '8', 'name' => 'Khawrihnim'],
            ['id' => '613', 'district_id' => '8', 'name' => 'Kolalian'],
            ['id' => '614', 'district_id' => '8', 'name' => 'K. Sarali'],
            ['id' => '615', 'district_id' => '8', 'name' => 'Lallen'],
            ['id' => '616', 'district_id' => '8', 'name' => 'Lengte'],
            ['id' => '617', 'district_id' => '8', 'name' => 'Lianbuang (Bega Bekya)'],
            ['id' => '618', 'district_id' => '8', 'name' => 'Luangpawl'],
            ['id' => '619', 'district_id' => '8', 'name' => 'Luimawi'],
            ['id' => '620', 'district_id' => '8', 'name' => 'Lungphun'],
            ['id' => '621', 'district_id' => '8', 'name' => 'Mamit Bazar Veng'],
            ['id' => '622', 'district_id' => '8', 'name' => 'Mamit Chhim Veng'],
            ['id' => '623', 'district_id' => '8', 'name' => 'Mamit Hmar Veng'],
            ['id' => '624', 'district_id' => '8', 'name' => 'Mamit Venghlun'],
            ['id' => '625', 'district_id' => '8', 'name' => 'Marpara Mizo Veng'],
            ['id' => '626', 'district_id' => '8', 'name' => 'Marpara North'],
            ['id' => '627', 'district_id' => '8', 'name' => 'Mualthuam'],
            ['id' => '628', 'district_id' => '8', 'name' => 'Nalzawl'],
            ['id' => '629', 'district_id' => '8', 'name' => 'New Eden'],
            ['id' => '630', 'district_id' => '8', 'name' => 'New Kawnpui'],
            ['id' => '631', 'district_id' => '8', 'name' => 'New Mamit'],
            ['id' => '632', 'district_id' => '8', 'name' => 'New West Phaileng'],
            ['id' => '633', 'district_id' => '8', 'name' => 'Nghalchawm'],
            ['id' => '634', 'district_id' => '8', 'name' => 'North Sabual'],
            ['id' => '635', 'district_id' => '8', 'name' => 'N.Tlangkhang'],
            ['id' => '636', 'district_id' => '8', 'name' => 'Parvatui'],
            ['id' => '637', 'district_id' => '8', 'name' => 'Phaizau'],
            ['id' => '638', 'district_id' => '8', 'name' => 'Phuldungdsei Zampui'],
            ['id' => '639', 'district_id' => '8', 'name' => 'Phuldungsei'],
            ['id' => '640', 'district_id' => '8', 'name' => 'Phulpui West'],
            ['id' => '641', 'district_id' => '8', 'name' => 'Pukzing'],
            ['id' => '642', 'district_id' => '8', 'name' => 'Pukzing Vengthar'],
            ['id' => '643', 'district_id' => '8', 'name' => 'Rajivnagar I'],
            ['id' => '644', 'district_id' => '8', 'name' => 'Rajiv Nagar II'],
            ['id' => '645', 'district_id' => '8', 'name' => 'Rawpuichhip'],
            ['id' => '646', 'district_id' => '8', 'name' => 'Reiek'],
            ['id' => '647', 'district_id' => '8', 'name' => 'Rengdil'],
            ['id' => '648', 'district_id' => '8', 'name' => 'Rulpuihlim'],
            ['id' => '649', 'district_id' => '8', 'name' => 'Saikhawthlir'],
            ['id' => '650', 'district_id' => '8', 'name' => 'Saithah'],
            ['id' => '651', 'district_id' => '8', 'name' => 'Serhmun West'],
            ['id' => '652', 'district_id' => '8', 'name' => 'Sihthiang'],
            ['id' => '653', 'district_id' => '8', 'name' => 'Silsury East'],
            ['id' => '654', 'district_id' => '8', 'name' => 'Silsury West'],
            ['id' => '655', 'district_id' => '8', 'name' => 'Sotapa'],
            ['id' => '656', 'district_id' => '8', 'name' => 'South Sabual'],
            ['id' => '657', 'district_id' => '8', 'name' => 'Suarhliap'],
            ['id' => '658', 'district_id' => '8', 'name' => 'Thaidawr'],
            ['id' => '659', 'district_id' => '8', 'name' => 'Thinghlun'],
            ['id' => '660', 'district_id' => '8', 'name' => 'Tuahzawl'],
            ['id' => '661', 'district_id' => '8', 'name' => 'Tuidam'],
            ['id' => '662', 'district_id' => '8', 'name' => 'Tuipuibari'],
            ['id' => '663', 'district_id' => '8', 'name' => 'Tuipuibari Venghlui'],
            ['id' => '664', 'district_id' => '8', 'name' => 'Tuirum'],
            ['id' => '665', 'district_id' => '8', 'name' => 'Tumpanglui'],
            ['id' => '666', 'district_id' => '8', 'name' => 'Vawngawnzo'],
            ['id' => '667', 'district_id' => '8', 'name' => 'West Lungdar'],
            ['id' => '668', 'district_id' => '8', 'name' => 'West Phaileng'],
            ['id' => '669', 'district_id' => '8', 'name' => 'West Serzawl'],
            ['id' => '670', 'district_id' => '8', 'name' => 'Zamuang'],
            ['id' => '671', 'district_id' => '8', 'name' => 'Zawlnuam Thuampui'],
            ['id' => '672', 'district_id' => '8', 'name' => 'Zawlnuam Vengpui'],
            ['id' => '673', 'district_id' => '8', 'name' => 'Zawlpui'],
            ['id' => '674', 'district_id' => '8', 'name' => 'Zomuantlang'],
            ['id' => '675', 'district_id' => '8', 'name' => 'Zopui'],
        ];

        Village::upsert($villages, ['id']);
    }
}
